### ISSUE TITLE
portal_historyGetEnr*/portal_historyDeleteEnr*/(anything that uses nodeid as param)  won't seralize properly

### ISSUE THREAD

**Issue by KolbyML** [ethereum/portal-hive#60]
This will either one fixed once we revert our semi NodeID transition to native sigp/enr library or we wait for the new version of sigp/enr which fixes this issue. So if we are in a rush we can just revert the semi done conversion PR and do the conversion after the new sigp/enr with the fixes is our. Or we can just wait till the new sigp/enr version with the fixes is out.

Either way after this is resolved I think in ethportal we should probably have a unit test which tests if all of the standard types in the spec serialize correctly. To provent this from happening again.

**Comment by ogenev** [comment]
I think we can wrap discv5 NodeId in our type until `enr` crate update the version (discv5 should also update the dependency version).

By wrapping I mean something similar to what we are doing with the bytes crate [here ](https://github.com/ethereum/trin/blob/b407f86f3e2fc28c6b37e7108634b61f3f867476/ethportal-api/src/types/wrapped/bytes.rs#L10). Then we should implement all `AsRef`, `From` and serialization traits for the new type and add back the tests.

> Either way after this is resolved I think in ethportal we should probably have a unit test which tests if all of the standard types in the spec serialize correctly

There were tests for `NodeId` but we removed them in https://github.com/ethereum/trin/pull/669.

**Comment by KolbyML** [comment]
Wouldn't that be the same as reverting https://github.com/ethereum/trin/pull/669

By adding the tests, I mean they should be in the tests folder instead of the wrappers file itself, and it's purpose should be labeled at the top like "tests all type serde according to spec". Since bytes has the "same" test, I think it would make sense to group them.

**Comment by KolbyML** [comment]
Here is a PR were I moved a few of the tests for now https://github.com/ethereum/trin/pull/794 and set it to use the NodeId wrapper we have
